#!/bin/bash

# Setup environment variables for CallWaiting AI
echo "🔧 Setting up environment variables..."

# Create .env.local from env.example
cp env.example .env.local

echo "✅ Created .env.local from env.example"
echo ""
echo "⚠️  IMPORTANT: You need to update .env.local with your actual values:"
echo ""
echo "1. Supabase Configuration:"
echo "   - Go to https://supabase.com/dashboard"
echo "   - Select your project"
echo "   - Go to Settings > API"
echo "   - Copy the Project URL and anon public key"
echo "   - Update NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo ""
echo "2. Supabase Service Role Key:"
echo "   - In the same API settings page"
echo "   - Copy the service_role secret key"
echo "   - Update SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "3. Google OAuth (Optional):"
echo "   - Go to https://console.cloud.google.com/"
echo "   - Create OAuth 2.0 credentials"
echo "   - Add http://localhost:3000/auth/callback to redirect URIs"
echo "   - Update GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET"
echo ""
echo "4. Other Services (Optional for testing):"
echo "   - Flutterwave: Get keys from https://dashboard.flutterwave.com/"
echo "   - MiniMax: Get API key from https://www.minimax.com/"
echo "   - OpenAI: Get API key from https://platform.openai.com/"
echo ""
echo "After updating .env.local, run: npm run dev"
echo ""
echo "📋 Next steps:"
echo "1. Update .env.local with your actual values"
echo "2. Run: npm run dev"
echo "3. Test the authentication system"
